Resources:
  SimpleEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0d2614eafc1b0e4d2
      Tags:
        - Key: Name
          Value: MySimpleInstance